# Generated by Django 6.0.2 on 2026-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮编'),
        ),
    ]
